{
 "title": "HTTP Metrics",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "Average HTTP Request Duration",
   "type": "barchart",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum(rate(demo_api_request_duration_seconds_sum[5m])) \r\nwithout (path, method) \r\n/\r\nsum(rate(demo_api_request_duration_seconds_count[5m])) \r\nwithout (path, method)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "95th Percentile for API HTTP Requests",
   "type": "bargauge",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 11 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "histogram_quantile(\r\n    0.95, \r\n    sum(rate(demo_api_request_duration_seconds_bucket[5m])) \r\n    without (path, method)\r\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "90th Percentile of HTTP Request Duration",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 24 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "histogram_quantile(\r\n    0.90, \r\n    sum(rate(demo_api_request_duration_seconds_bucket[5m])) \r\n    without (path, method, status)\r\n)",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}